"""Initial database schema setup

Revision ID: 62bed52eecfb
Revises: 
Create Date: 2025-05-17 17:02:33.706039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62bed52eecfb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_datasets',
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('dataset_id'),
    sa.UniqueConstraint('dataset_name')
    )
    op.create_table('journal_finder_service_configs',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('dataset_version', sa.String(length=50), nullable=True),
    sa.Column('last_sync_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('recommendation_engine_configs',
    sa.Column('engine_id', sa.Integer(), nullable=False),
    sa.Column('algorithm_name', sa.String(length=100), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('index_size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('engine_id')
    )
    op.create_table('system_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('admins',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('registered_users',
    sa.Column('registered_user_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('profile_data', sa.Text(), nullable=True),
    sa.Column('research_stats', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('registered_user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('collaboration_workspaces',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['registered_users.registered_user_id'], ),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_table('forum_posts',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('is_offensive', sa.Boolean(), nullable=True),
    sa.Column('author_registered_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_registered_user_id'], ['registered_users.registered_user_id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('sent_date', sa.DateTime(), nullable=False),
    sa.Column('recipient_registered_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_registered_user_id'], ['registered_users.registered_user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('premium_users',
    sa.Column('premium_user_id', sa.Integer(), nullable=False),
    sa.Column('registered_user_id', sa.Integer(), nullable=False),
    sa.Column('premium_since', sa.DateTime(), nullable=False),
    sa.Column('additional_quota', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['registered_user_id'], ['registered_users.registered_user_id'], ),
    sa.PrimaryKeyConstraint('premium_user_id'),
    sa.UniqueConstraint('registered_user_id')
    )
    op.create_table('research_papers',
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('owner_registered_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_registered_user_id'], ['registered_users.registered_user_id'], ),
    sa.PrimaryKeyConstraint('paper_id')
    )
    op.create_table('paper_metrics',
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('read_count', sa.Integer(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['research_papers.paper_id'], ),
    sa.PrimaryKeyConstraint('metric_id'),
    sa.UniqueConstraint('paper_id')
    )
    op.create_table('workspace_files',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['registered_users.registered_user_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['collaboration_workspaces.workspace_id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('workspace_members',
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['registered_users.registered_user_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['collaboration_workspaces.workspace_id'], ),
    sa.PrimaryKeyConstraint('membership_id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_user_membership')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_members')
    op.drop_table('workspace_files')
    op.drop_table('paper_metrics')
    op.drop_table('research_papers')
    op.drop_table('premium_users')
    op.drop_table('notifications')
    op.drop_table('forum_posts')
    op.drop_table('collaboration_workspaces')
    op.drop_table('registered_users')
    op.drop_table('admins')
    op.drop_table('users')
    op.drop_table('system_logs')
    op.drop_table('recommendation_engine_configs')
    op.drop_table('journal_finder_service_configs')
    op.drop_table('ai_datasets')
    # ### end Alembic commands ###
