"""Add paper management and forum features

Revision ID: cc03bd2f9b1b
Revises: 
Create Date: 2025-05-30 01:50:43.577541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc03bd2f9b1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_edited', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('topic_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_forum_post_topic', 'forum_topics', ['topic_id'], ['topic_id'])

    with op.batch_alter_table('research_papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('keywords', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_papers', schema=None) as batch_op:
        batch_op.drop_column('keywords')
        batch_op.drop_column('file_path')

    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_forum_post_topic', type_='foreignkey')
        batch_op.drop_column('topic_id')
        batch_op.drop_column('is_edited')

    # ### end Alembic commands ###
